# Generated by Django 3.1.5 on 2021-01-26 17:39

from django.db import migrations

def forward_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Subject = apps.get_model('school_timetable', 'Subject')
    Subject.objects.using(db_alias).bulk_create(
        [Subject(name='Физика', difficulty=12),
         Subject(name='Геометрия', difficulty=11),
         Subject(name='Химия', difficulty=11),
         Subject(name='Алгебра', difficulty=10),
         Subject(name='Русский язык', difficulty=9),
         Subject(name='Русская литература', difficulty=8),
         Subject(name='Ангийский язык', difficulty=8),
         Subject(name='Биология', difficulty=7),
         Subject(name='Информатика', difficulty=6),
         Subject(name='История', difficulty=5),
         Subject(name='Обществоведение', difficulty=5),
         Subject(name='Астрономия', difficulty=4),
         Subject(name='География', difficulty=3),
         Subject(name='ОБЖ', difficulty=2),
         Subject(name='Физ-ра', difficulty=1)]
    )

def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Subject = apps.get_model('school_timetable', 'Subject')
    Subject.objects.using(db_alias).filter(name='Физика').delete()
    Subject.objects.using(db_alias).filter(name='Геометрия').delete()
    Subject.objects.using(db_alias).filter(name='Химия').delete()
    Subject.objects.using(db_alias).filter(name='Алгебра').delete()
    Subject.objects.using(db_alias).filter(name='Русский язык').delete()
    Subject.objects.using(db_alias).filter(name='Русская литература').delete()
    Subject.objects.using(db_alias).filter(name='Ангийский язык').delete()
    Subject.objects.using(db_alias).filter(name='Биология').delete()
    Subject.objects.using(db_alias).filter(name='Информатика').delete()
    Subject.objects.using(db_alias).filter(name='История').delete()
    Subject.objects.using(db_alias).filter(name='Обществоведение').delete()
    Subject.objects.using(db_alias).filter(name='Астрономия').delete()
    Subject.objects.using(db_alias).filter(name='География').delete()
    Subject.objects.using(db_alias).filter(name='ОБЖ').delete()
    Subject.objects.using(db_alias).filter(name='Физ-ра').delete()



class Migration(migrations.Migration):

    dependencies = [
        ('school_timetable', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward_func,reverse_func)
    ]
