# Generated by Django 3.1.5 on 2021-01-26 18:11

from django.db import migrations


def forward_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Class = apps.get_model('school_timetable', 'Class')
    Class.objects.using(db_alias).bulk_create(
        [Class(character='А', grade=1),
         Class(character='Б', grade=1),
         Class(character='А', grade=2),
         Class(character='Б', grade=2),
         Class(character='А', grade=3),
         Class(character='Б', grade=3),
         Class(character='А', grade=4),
         Class(character='Б', grade=4),]
    )

def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Class = apps.get_model('school_timetable', 'Class')
    Class.objects.using(db_alias).filter(character='А', grade=1).delete()
    Class.objects.using(db_alias).filter(character='Б', grade=1).delete()
    Class.objects.using(db_alias).filter(character='А', grade=2).delete()
    Class.objects.using(db_alias).filter(character='Б', grade=2).delete()
    Class.objects.using(db_alias).filter(character='А', grade=3).delete()
    Class.objects.using(db_alias).filter(character='Б', grade=3).delete()
    Class.objects.using(db_alias).filter(character='А', grade=4).delete()
    Class.objects.using(db_alias).filter(character='Б', grade=4).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('school_timetable', '0002_add_subjects'),
    ]

    operations = [
        migrations.RunPython(forward_func,reverse_func)
    ]
